---

- name: Setup data directory
  ansible.builtin.file:
    path: "{{ amq_broker_data_dir }}"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    mode: u=rwx,g=rwx,o=
    state: directory
  when: amq_broker_data_dir | default("") | length > 0
  tags:
    - role::amq::install
    - role::amq::install::storage
