---
# Download tasks

- block:
    - name: Setup install directory
      file:
        path: "{{ amq_install_dir | dirname }}"
        state: directory
        owner: "{{ amq_user }}"
        group: "{{ amq_group }}"
        mode: u=rwx,g=rwx,o=rx

    - name: Download amq artifact
      include_tasks: artifact.yml
      when: >-
        not ansible_local.artifact_amq_artifact.version | default ("")
        == amq_version
  tags:
    - role::amq::install
    - role::amq::install::download
