---

- name: Check for amq service file
  ansible.builtin.stat:
    path: /usr/lib/systemd/system/amq.service
  register: amq_service_result

- name: Stop amq service if present
  when: amq_service_result.stat.exists
  ansible.builtin.systemd:
    name: amq
    enabled: yes
    state: stopped

- name: Kill java when active
  ansible.builtin.command: /usr/bin/pkill java
  register: pkill_result
  changed_when: pkill_result.rc | int == 0
  failed_when: no

- name: Erase all amq files and dirs if present
  ansible.builtin.file:
    path: "{{ file }}"
    state: absent
  loop:
    - /etc/ansible/facts.d/artifact_amq_artifact.fact
    - "{{ amq_base_dir }}"
  loop_control:
    loop_var: file

- name: Unmount shared nfs directory
  mount:
    path: "{{ amq_broker_data_dir }}"
    state: unmounted

- name: Erase all amq files and dirs if present
  ansible.builtin.file:
    path: "{{ amq_base_dir }}"
    state: absent
