---

- name: Verify xml
  vars:
    config_dir: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc"
  block:
    - name: Install python lxml
      ansible.builtin.pip:
        name: lxml

    - name: Verify xml node values
      community.general.xml:
        path: "{{ config_dir }}/{{ node.path }}"
        xpath: "{{ node.xpath }}"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        value: >-
          {{ node.value
          | ternary("true", "false") }}
        backup: yes
      check_mode: yes
      loop_control:
        loop_var: node
        label: "{{ node.label }}"
      loop:
        - label: amq_broker_enable_destination_autocreate auto-create-queues
          path: broker_address_settings.xml
          xpath: >-
            {{ '/core:address-settings/'
            + 'core:address-setting[@match="#"]/core:auto-create-queues' }}
          value: "{{ amq_broker_enable_destination_autocreate }}"

        - label: amq_broker_enable_destination_autocreate auto-create-addresses
          path: broker_address_settings.xml
          xpath: >-
            {{ '/core:address-settings/'
            + 'core:address-setting[@match="#"]/core:auto-create-addresses' }}
          value: "{{ amq_broker_enable_destination_autocreate }}"

        - label: amq_broker_enable_destination_autocreate auto-create-jms-queues
          path: broker_address_settings.xml
          xpath: >-
            {{ '/core:address-settings/'
            + 'core:address-setting[@match="#"]/core:auto-create-jms-queues' }}
          value: "{{ amq_broker_enable_destination_autocreate }}"

        - label: amq_broker_enable_destination_autocreate auto-create-jms-topics
          path: broker_address_settings.xml
          xpath: >-
            {{ '/core:address-settings/'
            + 'core:address-setting[@match="#"]/core:auto-create-jms-topics' }}
          value: "{{ amq_broker_enable_destination_autocreate }}"
      register: xml_node_verification

    - name: Check xml node values verificarion
      ansible.builtin.assert:
        # Fail if anything changes
        that: >-
          not (xml_node_verification.results
          | json_query('[].changed')
          | max )
        # max == (any true → 1 ; all false → 0)
        msg: "Verifications should not change values"
