---
- name: Setup prerequisites
  ansible.builtin.include_tasks:
    file: prerequisites.yml

- name: Check amq
  ansible.builtin.include_tasks:
    file: check.yml

- name: Install amq
  ansible.builtin.include_tasks:
    file: install/main.yml

- name: Configure amq
  ansible.builtin.include_tasks:
    file: configure/main.yml
