---
- name: Check amq
  ansible.builtin.import_tasks: check.yml

- name: Install amq
  ansible.builtin.import_tasks: install/main.yml

- name: Configure amq
  ansible.builtin.import_tasks: configure/main.yml
