---

- name: Enable and start amq broker service
  ansible.builtin.systemd:
    name: amq
    state: restarted
  when: amq_item.flag
  loop:
    - flag: "{{ not amq_broker_is_replica }}"
      label: Primary turn
    - flag: "{{ amq_broker_is_replica }}"
      label: Replica turn
  loop_control:
    loop_var: amq_item
    label: "{{ amq_item.label }}"
    pause: 10
  listen:
    - enable and start amq broker
    - enable amq broker
    - start amq broker
    - restart amq broker
