---
# Role handlers

- name: Enable and start amq broker service
  systemd:
    name: amq
    state: restarted
  when: amq_item.flag
  loop:
    - flag: "{{ not amq_broker_is_slave }}"
      label: Master turn
    - flag: "{{ amq_broker_is_slave }}"
      label: Slave turn
  loop_control:
    loop_var: amq_item
    label: "{{ amq_item.label }}"
    pause: 10
  listen:
    - enable and start amq broker
    - enable amq broker
    - start amq broker
    - restart amq broker
