---

- name: Pre - Converge
  hosts: molecule_hosts_amq_cluster
  tasks:
    - name: Molecule requirements for this scenario
      include_tasks: scenario_requirements.yml
  vars:
    ansible_python_interpreter: >-
      {{ (inventory_hostname in groups.molecule_hosts_centos_7)
         | ternary("/usr/bin/python", "/usr/bin/python3") }}

- name: Converge
  hosts: molecule_hosts_amq_cluster
  become: yes
  become_user: root
  roles:
    - amtega.amq
  vars:
    ansible_python_interpreter: >-
      {{ (inventory_hostname in groups.molecule_hosts_centos_7)
         | ternary("/usr/bin/python", "/usr/bin/python3") }}
