---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "nfs-${INSTANCE_UUID:-1}"
    box: ${VAGRANT_BOX:-centos/stream8}
    provider_options:
      gui: no
    provider_raw_config_args:
      - 'customize ["modifyvm", :id, "--graphicscontroller", "none"]'
      - 'customize ["modifyvm", :id, "--vram", "0"]'
      # Disable audio
      - 'customize ["modifyvm", :id, "--audio", "none"]'
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: yes
    groups:
      - molecule_hosts
      - molecule_hosts_nfs_servers
  - name: "primary-${INSTANCE_UUID:-1}"
    box: ${VAGRANT_BOX:-centos/stream8}
    provider_options:
      gui: no
    provider_raw_config_args:
      # Disable video
      - 'customize ["modifyvm", :id, "--graphicscontroller", "none"]'
      - 'customize ["modifyvm", :id, "--vram", "0"]'
      # Disable audio
      - 'customize ["modifyvm", :id, "--audio", "none"]'
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: yes
    groups:
      - molecule_hosts
      - molecule_hosts_amq_cluster
      - molecule_hosts_amq_primary
  - name: "replica-${INSTANCE_UUID:-1}"
    box: ${VAGRANT_BOX:-centos/stream8}
    provider_options:
      gui: no
    provider_raw_config_args:
      - 'customize ["modifyvm", :id, "--graphicscontroller", "none"]'
      - 'customize ["modifyvm", :id, "--vram", "0"]'
      - 'customize ["modifyvm", :id, "--audio", "none"]'
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: yes
    groups:
      - molecule_hosts
      - molecule_hosts_amq_cluster
      - molecule_hosts_amq_replicas
provisioner:
  name: ansible
  ansible_args:
    - --inventory=${ANSIBLE_INVENTORY}
    - --vault-password-file=${ANSIBLE_VAULT_PASSWORD_FILE:-/etc/hostname}
  inventory:
    hosts:
      molecule_hosts:
        vars:
          instance_uuid: "${INSTANCE_UUID:-1}"
          ansible_user: root

          # Save created files for further study
          test_save_files: no
          test_saved_files_dir: ${MOLECULE_SCENARIO_DIRECTORY}/output

          test_nfs_server_ip: >-
            {{ (hostvars[groups.molecule_hosts_nfs_servers.0]
               ).ansible_eth1.ipv4.address }}

          test_nfs_directory: /nfsfileshare
          test_nfs_share: "{{ test_nfs_server_ip }}:{{ test_nfs_directory }}"

          test_primary_ip: >-
            {{ (hostvars[groups.molecule_hosts_amq_primary.0]
               ).ansible_eth1.ipv4.address }}

          test_replica_ip: >-
            {{ (hostvars[groups.molecule_hosts_amq_replicas.0]
               ).ansible_eth1.ipv4.address }}

          test_java_package: java-1.8.0-openjdk

          amq_version: 7.8.3

          amq_user: amq-broker
          amq_group: amq-broker

          amq_broker_name: "{{ inventory_hostname }}"
          amq_base_dir: /opt/redhat/amq-broker
          amq_install_dir: >-
            {{ amq_base_dir }}/install/amq-broker-{{ amq_version }}
          amq_brokers_dir: "{{ amq_base_dir }}/brokers"
          amq_broker_data_dir: /mnt/share-amqbroker/test_instance

          amq_broker_java_options:
            - param: "-Djava.net.preferIPv4Stack="
              value: "true"
            - param: "-Xms"
              value: "512M"
            - param: "-Xmx"
              value: "2G"
            - param: '-Dhawtio.roles="'
              value: '{{ amq_broker_admin_groups | join(",") }}"'

          amq_broker_admin:
            name: admin
            password: test_pass
            role: admin

          amq_broker_admin_groups:
            - admin

          amq_broker_cluster_discovery: no
          amq_broker_shared_store: yes
          amq_broker_cluster_maxhops: 1
          amq_broker_cluster_load_balancing_policy: STRICT
          amq_broker_address_setting_redelivery_delay: 500
          # broker.xml:/configuration/core/global-max-size=512M
          # amq_broker_global_max_size = amq_broker_java_options.param Xmx / 4
          amq_broker_global_max_size: 512M
          amq_broker_security_invalidation_interval: 3600000

          amq_broker_http_host_bindings: 0.0.0.0

          amq_broker_nio: no
          amq_broker_nio_remoting_threads: -1
          amq_broker_amqp_low_credits: 30

          amq_broker_aio: yes
          amq_broker_journal_max_io: 500

          amq_broker_security_settings:
            - address: "#"
              permissions:
                createNonDurableQueue:
                  - admin
                deleteNonDurableQueue:
                  - admin
                createDurableQueue:
                  - admin
                deleteDurableQueue:
                  - admin
                createAddress:
                  - admin
                deleteAddress:
                  - admin
                consume:
                  - admin
                browse:
                  - admin
                send:
                  - admin
                manage:
                  - admin
          amq_jolokia_allowed_origins: >-
            {{
              ([ "*://localhost*",
              "*://" + ansible_facts.fqdn + "*" ]
              + ansible_all_ipv4_addresses
              | map('regex_replace', '^(.*)', '*://\1*'))
              | sort
              | unique
            }}

          amq_broker_enable_destination_autocreate: no

          amq_no_log: no
      molecule_hosts_amq_primary:
        vars:
          amq_broker_is_replica: no
      molecule_hosts_amq_replicas:
        vars:
          amq_broker_is_replica: yes
verifier:
  name: ansible
