---

- name: Prepare testing hosts
  hosts: molecule_hosts
  gather_facts: no
  become: yes
  tasks:
    - name: Setup python
      raw: "yum install -y {{ ansible_python_interpreter | basename }}"
      changed_when: no
      when: yes

    - name: Gather facts
      setup:

    - name: Match vagrant vm name to inventory
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Remove loopback (/etc/hosts)
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '^127\.0\.0\.1'
        line:
        owner: root
        group: root
        mode: "0644"
        backup: yes

    - name: Add primary and replica to DNS (/etc/hosts) HARDCODED
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        owner: root
        group: root
        mode: "0644"
        backup: yes
      loop:
        - "{{ test_primary_ip }} primary-{{ instance_uuid }}"
        - "{{ test_replica_ip }} replica-{{ instance_uuid }}"
  vars:
    ansible_python_interpreter: >-
      {{ (inventory_hostname in groups.molecule_hosts_centos_7)
         | ternary("/usr/bin/python", "/usr/bin/python3") }}

- name: Prepare nfs server
  hosts: molecule_hosts_nfs_servers
  become: yes
  tasks:
    - name: Molecule requirements for this scenario
      include_tasks: scenario_requirements.yml

    - name: Setup packages
      yum:
        state: present
        name:
          - nfs-utils
          - rpcbind

    - name: Setup /etc/exports
      lineinfile:
        path: /etc/exports
        line: "{{ test_nfs_directory }} *(rw,sync,no_root_squash,no_all_squash)"
        create: yes
        mode: 0644

    - name: Setup nfs shared directory
      file:
        path: "{{ test_nfs_directory }}"
        state: directory
        mode: "755"
        owner: nobody
        group: nobody

    - name: Start and enable service
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - rpcbind
        - nfs-server
        - nfs-lock
        - nfs-idmap

    - name: Setup nfs-server service
      systemd:
        name: nfs-server
        state: restarted
  vars:
    ansible_python_interpreter: >-
      {{ (inventory_hostname in groups.molecule_hosts_centos_7)
         | ternary("/usr/bin/python", "/usr/bin/python3") }}

- name: Prepare amq cluster hosts
  hosts: molecule_hosts_amq_cluster
  become: yes
  tasks:
    - name: Setup packages
      yum:
        state: present
        name:
          - "{{ test_java_package }}"
          - nfs-utils

    - name: "Ensure group {{ amq_group }} exists"
      group:
        name: "{{ amq_group }}"
        state: present

    - name: "Ensure user {{ amq_user }} exists"
      user:
        name: "{{ amq_user }}"
        group: "{{ amq_group }}"

    - name: Clean amq if installed
      import_tasks: prepare_clean.yml

    # HACK: Need mount point, made in advance.
    #       Same as tasks/install/data_dir.yml
    - name: Setup data directory
      file:
        path: "{{ amq_broker_data_dir }}"
        owner: "{{ amq_user }}"
        group: "{{ amq_group }}"
        mode: u=rwx,g=rwx,o=
        state: directory
        recurse: yes

    - name: Mount shared nfs directory
      mount:
        path: "{{ amq_broker_data_dir }}"
        src: "{{ test_nfs_share }}"
        fstype: nfs
        opts: rw
        state: mounted
  vars:
    ansible_python_interpreter: >-
      {{ (inventory_hostname in groups.molecule_hosts_centos_7)
         | ternary("/usr/bin/python", "/usr/bin/python3") }}
