---

# test_saved_files_dir

- name: Verify xml
  vars:
    config_dir: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc"
  block:

    - name: Verify xml node values
      xml:
        path: "{{ config_dir }}/{{ node.path }}"
        xpath: "{{ node.xpath }}"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        value: >-
          {{ amq_broker_enable_destination_autocreate
          | ternary("true", "false") }}
      loop_control:
        loop_var: node
        label: "{{ node.label }}"
      loop:
        - label: amq_broker_enable_destination_autocreate auto-create-queues
          path: broker.xml
          xpath: >-
            {{ '/conf:configuration/core:core/core:address-settings/'
            + 'core:address-setting[@match="#"]/core:auto-create-queues' }}
          value: >-
            {{ amq_broker_enable_destination_autocreate
            | ternary("true", "false") }}
        - label: amq_broker_enable_destination_autocreate auto-create-addresses
          path: broker.xml
          xpath: >-
            {{ '/conf:configuration/core:core/core:address-settings/'
            + 'core:address-setting[@match="#"]/core:auto-create-addresses' }}
          value: >-
            {{ amq_broker_enable_destination_autocreate
            | ternary("true", "false") }}
        - label: amq_broker_enable_destination_autocreate auto-create-jms-queues
          path: broker.xml
          xpath: >-
            {{ '/conf:configuration/core:core/core:address-settings/'
            + 'core:address-setting[@match="#"]/core:auto-create-jms-queues' }}
          value: >-
            {{ amq_broker_enable_destination_autocreate
            | ternary("true", "false") }}
        - label: amq_broker_enable_destination_autocreate auto-create-jms-topics
          path: broker.xml
          xpath: >-
            {{ '/conf:configuration/core:core/core:address-settings/'
            + 'core:address-setting[@match="#"]/core:auto-create-jms-topics' }}
          value: >-
            {{ amq_broker_enable_destination_autocreate
            | ternary("true", "false") }}
