---

- name: Verify
  hosts: molecule_hosts
  become: yes
  tasks:

    - name: Molecule requirements for this scenario
      include_tasks: scenario_requirements.yml

- name: Get historic
  hosts: molecule_hosts_amq_cluster
  become: yes
  tasks:

    - name: Save created VM files
      when: test_save_files
      include_tasks: verify_save_files.yml
