---

- name: Verify
  hosts: molecule_hosts
  become: yes
  tasks:
    - name: Molecule requirements for this scenario
      include_tasks: scenario_requirements.yml
  vars:
    ansible_python_interpreter: >-
      {{ (inventory_hostname in groups.molecule_hosts_centos_7)
         | ternary("/usr/bin/python", "/usr/bin/python3") }}

- name: Get historic
  hosts: molecule_hosts_amq_cluster
  become: yes
  tasks:
    - name: Save created VM files
      when: test_save_files
      include_tasks: verify_save_files.yml

    - name: Verify xml
      include_tasks: verify_xml.yml
  vars:
    ansible_python_interpreter: >-
      {{ (inventory_hostname in groups.molecule_hosts_centos_7)
         | ternary("/usr/bin/python", "/usr/bin/python3") }}
