---
# Configure artemis tasks

- name: Configure artemis profile
  vars:
    desired_option: >-
      -Dhawtio.roles="{{ amq_broker_admin_groups | join(',') }}"
  lineinfile:
    path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/artemis.profile"
    regexp: '^(JAVA_ARGS=.*)(-Dhawtio\.role?=[^ ]* )(.*)$'
    line: '\1{{ desired_option }}\3'
    backrefs: yes
    backup: yes
  tags:
    - role::amq::configure
    - role::amq::configure::artemis
