---
# Configure artemis tasks

- name: Configure artemis JAVA_ARGS
  block:
    - name: Get artemis JAVA_ARGS
      command: >-
        /bin/grep "^ *JAVA_ARGS=" {{ ini_file }}
      changed_when: no
      register: get_java_args_result

    - name: Configure artemis JAVA_ARGS
      vars:
        configured_java_args: >-
          {{ get_java_args_result.stdout
          | merge_java_parameters(amq_broker_java_options) }}
      lineinfile:
        path: "{{ ini_file }}"
        regexp: '^ *JAVA_ARGS=.*$'
        line: "{{ configured_java_args }}"
        backup: yes
  vars:
    ini_file: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/artemis.profile"
  tags:
    - role::amq::configure
    - role::amq::configure::artemis
