---
# Configure broker tasks

- name: Configure broker tasks
  block:
    - name: Setup fact with broker cluster node members
      ansible.builtin.set_fact:
        amq_broker_cluster_nodes: >
          {{ amq_broker_cluster_nodes | default([])
             + [
                 {
                   "name": hostvars[amq_broker_node_item].amq_broker_name,
                   "address": hostvars[amq_broker_node_item].ansible_facts.fqdn,
                   "inventory_host": hostvars[amq_broker_node_item]
                                     .ansible_facts.fqdn,
                   "value": "tcp://" + hostvars[amq_broker_node_item]
                                       .ansible_facts.fqdn + ":61616"
                 }
              ] }}
      loop: "{{ ansible_play_hosts_all }}"
      loop_control:
        loop_var: amq_broker_node_item

    - name: Setup broker directory
      ansible.builtin.file:
        path: "{{ amq_brokers_dir }}"
        state: directory
        owner: "{{ amq_user }}"
        group: "{{ amq_group }}"
        recurse: yes

    - name: Create broker
      when: amq_broker_primary_replica_flag.flag
      ansible.builtin.command: >-
        {{ amq_install_dir }}/bin/artemis create
        {{ amq_brokers_dir }}/{{ amq_broker_name }}
        {{ amq_broker_options }}
      args:
        creates: "{{ amq_brokers_dir }}/{{ amq_broker_name }}"
      notify: restart amq broker
      loop:
        - flag: "{{ not amq_broker_is_replica }}"
          label: Primary turn
        - flag: "{{ amq_broker_is_replica }}"
          label: Replica turn
      loop_control:
        loop_var: amq_broker_primary_replica_flag
        label: "{{ amq_broker_primary_replica_flag.label }}"
        pause: 5
      become: yes
      no_log: "{{ amq_no_log | bool }}"
      vars:
        ansible_become_user: "{{ amq_user }}"
        amq_broker_options: >-
          {{ lookup('template', 'broker_options.j2').split("\n") | join(' ') }}

    - name: Configure addresses node in broker.xml to broker_addresses.xml
      include_tasks: xml_to_include.yml
      vars:
        xml_source: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xml_destination: >-
          {{ amq_brokers_dir }}/{{ amq_broker_name
          }}/etc/broker_addresses.xml
        xml_destination_owner: "{{ amq_user }}"
        xml_destination_group: "{{ amq_group }}"
        node_name: addresses
        node_parent_xpath: /conf:configuration/core:core
        node_xpath: "{{ node_parent_xpath }}/core:{{ node_name }}"
        node_namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        node_content: >-
          {{ lookup("template", "broker_addresses.xml.j2") }}
        node_backup: yes
        overwrite_existing_include: no

    - name: >-
        Configure address-settings node in broker.xml
        to broker_address_settings.xml
      include_tasks: xml_to_include.yml
      vars:
        xml_source: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xml_destination: >-
          {{ amq_brokers_dir }}/{{ amq_broker_name
          }}/etc/broker_address_settings.xml
        xml_destination_owner: "{{ amq_user }}"
        xml_destination_group: "{{ amq_group }}"
        node_name: address-settings
        node_parent_xpath: /conf:configuration/core:core
        node_xpath: "{{ node_parent_xpath }}/core:{{ node_name }}"
        node_namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        node_content: "{{ amq_broker_address_settings_xml }}"
        node_backup: yes
        overwrite_existing_include: no

    - name: >-
        Configure security-settings node in broker.xml
        to broker_security_settings.xml
      include_tasks: xml_to_include.yml
      vars:
        xml_source: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xml_destination: >-
          {{ amq_brokers_dir }}/{{ amq_broker_name
          }}/etc/broker_security_settings.xml
        xml_destination_owner: "{{ amq_user }}"
        xml_destination_group: "{{ amq_group }}"
        node_name: security-settings
        node_parent_xpath: /conf:configuration/core:core
        node_xpath: "{{ node_parent_xpath }}/core:{{ node_name }}"
        node_namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        node_content: >-
          {{ lookup("template", "broker_security_settings.xml.j2") }}
        node_backup: yes
        overwrite_existing_include: no

    - name: Configure broker global max size
      xml:
        path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: >-
          {{ "/conf:configuration/core:core/core:global-max-size" }}
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        value: >-
          {{ amq_broker_global_max_size | string | upper }}
        backup: yes

    - name: Configure broker discovery group
      when: amq_broker_cluster_discovery | bool
      block:
        - name: Configure - jgroups - broker.xml - discovery-group-ref
          when: amq_jgroups_enabled | bool
          xml:
            path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
            xpath: >-
              {{ "/conf:configuration/core:core/core:cluster-connections/"
              + "core:cluster-connection/core:discovery-group-ref" }}
            namespaces:
              conf: urn:activemq
              core: urn:activemq:core
            attribute: discovery-group-name
            value: discovery-group-01
            pretty_print: yes
            backup: yes

        - name: Configure broker discovery groups node
          when: amq_jgroups_enabled | bool
          xml:
            path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
            xpath: "/conf:configuration/core:core/core:discovery-groups"
            namespaces:
              conf: urn:activemq
              core: urn:activemq:core
            state: present
            pretty_print: yes
            backup: yes

        - name: Configure broker discovery groups content
          when: amq_jgroups_enabled | bool
          xml:
            path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
            xpath: "/conf:configuration/core:core/core:discovery-groups"
            namespaces:
              conf: urn:activemq
              core: urn:activemq:core
            set_children:
              - "discovery-group":
                  name: discovery-group-01
                  _:
                    - "jgroups-file": "{{ amq_jgroups_file }}"
                    - "jgroups-channel": "{{ amq_jgroups_channel }}"
                    - "refresh-timeout": "{{ amq_jgroups_refresh_timeout }}"
            pretty_print: yes
            backup: yes

        - name: Configure broker broadcast groups node
          when: amq_jgroups_enabled | bool
          xml:
            path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
            xpath: "/conf:configuration/core:core/core:broadcast-groups"
            namespaces:
              conf: urn:activemq
              core: urn:activemq:core
            state: present
            pretty_print: yes
            backup: yes

        - name: Configure broker broadcast groups content
          when: amq_jgroups_enabled | bool
          xml:
            path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
            xpath: "/conf:configuration/core:core/core:broadcast-groups"
            namespaces:
              conf: urn:activemq
              core: urn:activemq:core
            set_children:
              - "broadcast-group":
                  name: broadcast-group-01
                  _:
                    - "broadcast-period": "5000"
                    - "jgroups-file": "{{ amq_jgroups_file }}"
                    - "jgroups-channel": "{{ amq_jgroups_channel }}"
                    - "connector-ref": "{{ amq_jgroups_connector_ref }}"
            pretty_print: yes
            backup: yes

    - name: Configure broker security invalidation interval node
      xml:
        path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: >-
          /conf:configuration/core:core/core:security-invalidation-interval
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        value: "{{ amq_broker_security_invalidation_interval | string }}"
        state: present
        pretty_print: yes
        backup: yes

    - name: Configure broker queue depth for libaio
      when: amq_broker_aio
      xml:
        path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: >-
          /conf:configuration/core:core/core:journal-max-io
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        value: "{{ amq_broker_journal_max_io | string }}"
        state: present
        pretty_print: yes
        backup: yes

    - name: Configure maximum number of thread used by the general thread pool
      xml:
        path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: >-
          /conf:configuration/core:core/core:thread-pool-max-size
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        value: "{{ amq_broker_thread_pool_max_size | string }}"
        state: present
        pretty_print: yes
        backup: yes

    - name: Configure maximum number of thread used by the scheduled thread pool
      xml:
        path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: >-
          /conf:configuration/core:core/core:scheduled-thread-pool-max-size
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        value: "{{ amq_broker_scheduled_thread_pool_max_size | string }}"
        state: present
        pretty_print: yes
        backup: yes

    - name: Configure metrics node (for Prometheus)
      xml:
        path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: "/conf:configuration/core:core/core:metrics"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        state: present
        pretty_print: yes
        backup: yes

    - name: Configure metrics content
      xml:
        path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: "/conf:configuration/core:core/core:metrics"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        set_children:
          - "jvm-gc": "true"
          - "jvm-memory": "true"
          - "jvm-threads": "true"
          - plugin:
              "class-name": >-
                {{ "org.apache.activemq.artemis.core.server.metrics.plugins"
                + ".ArtemisPrometheusMetricsPlugin" }}
        pretty_print: yes
        backup: yes

    - name: Apply thread and credit configuration in artemis acceptor
      when: amq_broker_aio | bool
      include_tasks: acceptor.yml
      vars:
        acceptor_name: artemis
        acceptor_configuration:
          query:
            nioRemotingThreads: "{{ amq_broker_nio_remoting_threads }}"
            amqpLowCredits: "{{ amq_broker_amqp_low_credits }}"
  tags:
    - role::amq::configure
    - role::amq::configure::broker
