---

- name: Configure addresses node in broker.xml
  vars:
    etc_broker_path: >-
      {{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml
    etc_broker_addresses_path: >-
      {{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker_addresses.xml
    backup: yes
  block:

    - name: Remove addresses node
      xml:
        path: "{{ etc_broker_path }}"
        xpath: /conf:configuration/core:core/core:addresses
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core

    - name: Template broker_connectors.xml
      template:
        src: broker_addresses.xml.j2
        dest: "{{ etc_broker_addresses_path }}"
        owner: "{{ amq_user }}"
        group: "{{ amq_group }}"
      register: broker_addresses_result

    - name: Trigger configuration reload on broker_addresses.xml change
      # When an included file changes, parent file needs to be touched to
      #  trigger service configuration reload
      when: broker_addresses_result is changed
      file:
        path: "{{ etc_broker_path }}"
        state: touch

    - name: Count broker addresses includes
      xml:
        path: "{{ etc_broker_path }}"
        xpath: >-
          /conf:configuration/core:core/xi:include[@href='{{
          etc_broker_addresses_path }}']
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
          xi: "http://www.w3.org/2001/XInclude"
        count: yes
      register: broker_addresses_include_count_result

    - name: Add broker addresses include
      when: broker_addresses_include_count_result.count == 0
      xml:
        path: "{{ etc_broker_path }}"
        xpath: >-
          /conf:configuration/core:core/xi:include[@href='{{
          etc_broker_addresses_path }}']
        attribute: href
        value: "{{ etc_broker_addresses_path }}"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
          xi: "http://www.w3.org/2001/XInclude"
        pretty_print: yes
        backup: "{{ backup }}"
