---
# Configure clustering tasks

- name: Configure static cluster connectors
  when: >-
    amq_broker_cluster | bool
    and not amq_broker_cluster_discovery | bool
  vars:
    etc_broker_path: >-
      {{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml
    backup: yes
    query: >-
      [?contains(value, `{{ ansible_host }}`) != `true`
      && contains(value, `{{ ansible_facts.fqdn }}`) != `true` ].name
      | sort(@)
    expected_connectors: >-
      {{ amq_broker_cluster_nodes
      | json_query( query )
      | sort
      | list }}
    query2: >-
      [?contains(value, `{{ ansible_host }}`) != `true`
      && contains(value, `{{ ansible_facts.fqdn }}`) != `true`
      ].{name: name, value: value}
      | sort_by(@, &name)
    constructed_connectors: >-
      {{ amq_broker_cluster_nodes
      | json_query(query2)
      | list }}
  tags:
    - role::amq::configure
    - role::amq::configure::clustering
  block:

    - name: Set cluster-connections
      xml:
        path: "{{ etc_broker_path }}"
        xpath: /conf:configuration/core:core/core:cluster-connections
        set_children: "{{ lookup('template', 'broker_cluster_connections.xml.j2') }}"
        input_type: xml
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: yes
        backup: "{{ backup }}"

    - name: Set connector
      xml:
        path: "{{ etc_broker_path }}"
        xpath: /conf:configuration/core:core/core:connectors
        set_children: "{{ lookup('template', 'connector.xml.j2') }}"
        input_type: xml
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: yes
        backup: "{{ backup }}"

    - name: Remove cluster connection discovery group reference
      xml:
        path: "{{ etc_broker_path }}"
        xpath: >-
          {{ "/conf:configuration/core:core/core:cluster-connections/"
          + "core:cluster-connection/core:discovery-group-ref" }}
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: "{{ backup }}"

    - name: Remove broadcast groups
      xml:
        path: "{{ etc_broker_path }}"
        xpath: /conf:configuration/core:core/core:broadcast-groups
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: "{{ backup }}"

    - name: Remove discovery groups
      xml:
        path: "{{ etc_broker_path }}"
        xpath: /conf:configuration/core:core/core:discovery-groups
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: "{{ backup }}"
