---
# Configure clustering tasks

- name: Configure static cluster connectors
  when: >-
    amq_broker_cluster
    and not amq_broker_cluster_discovery | bool
  vars:
    etc_broker_path: >-
      {{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml
    xpath_root: >-
      {{ "/conf:configuration/core:core/core:cluster-connections/"
      + "core:cluster-connection" }}
    backup: yes
    query: >-
      [?contains(value, `{{ ansible_host }}`) != `true`].name
      | sort(@)
    expected_connectors: >-
      {{ amq_broker_cluster_nodes
      | json_query( query )
      | sort
      | list }}
    constructed_connectors: >-
      {{ expected_connectors
      | json_query( 'map(&{"connector-ref": @},  @)' )
      | list }}
  tags:
    - role::amq::configure
    - role::amq::configure::clustering
  block:
    - debug:
        var: amq_broker_cluster_nodes
    - debug:
        var: query
    - debug:
        var: constructed_connectors
    - name: Get number of static-connectors nodes
      xml:
        path: "{{ etc_broker_path }}"
        xpath: "{{ xpath_root + '/core:static-connectors' }}"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        count: yes
      register: static_connectors_count_result

    - debug:
        var: static_connectors_count_result

    - name: Add static-connectors node
      when: static_connectors_count_result.count == 0
      xml:
        path: "{{ etc_broker_path }}"
        xpath: "{{ xpath_root }}"
        add_children:
          - static-connectors:
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: yes
        backup: "{{ backup }}"


    - debug:
        var: query

    - debug:
        var: amq_broker_cluster_nodes

    - debug:
        var: expected_connectors

    - debug:
        var: constructed_connectors

    - name: Add static-connectors/connector nodes
      xml:
        path: "{{ etc_broker_path }}"
        xpath: "{{ xpath_root + '/core:static-connectors' }}"
        set_children: "{{ constructed_connectors }}"
          # - connector:
          #     name: "{{ name | string }}"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: yes
        backup: "{{ backup }}"
      loop: "{{ expected_connectors }}"
      loop_control:
        loop_var: name

- block:

    - name: Remove cluster connection discovery group reference
      xml:
        path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: >-
          {{ '/conf:configuration/core:core/core:cluster-connections/'
          + 'core:cluster-connection/core:discovery-group-ref' }}
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: yes
      when: not amq_broker_cluster_discovery | bool

    - name: Remove broadcast groups
      xml:
        path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: /conf:configuration/core:core/core:broadcast-groups
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: yes
      when: not amq_broker_cluster_discovery | bool

    - name: Remove discovery groups
      xml:
        path: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: /conf:configuration/core:core/core:discovery-groups
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: yes
      when: not amq_broker_cluster_discovery | bool

  when: amq_broker_cluster
  tags:
    - role::amq::configure
    - role::amq::configure::clustering
