---
# Configure clustering tasks

- block:
    - name: Gather static connectors
      xml:
        path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: /conf:configuration/core:core/core:connectors/core:connector
        content: text
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: yes
      when: not amq_broker_cluster_discovery
      register: amq_connectors_result

    - name: Add static connectors
      vars:
        connectors: >-
          {{ amq_connectors_result
             | json_query('matches[*].*')
             | json_query('[]') }}
      xml:
        path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: /conf:configuration/core:core/core:connectors
        add_children:
          - connector:
              name: "{{ amq_broker_cluster_node_item.name | string }}"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: yes
        backup: yes
      when: >-
        not amq_broker_cluster_discovery
        and not amq_broker_cluster_node_item.value is search(ansible_host)
        and not amq_broker_cluster_node_item.value in connectors
      loop: "{{ amq_broker_cluster_nodes }}"
      loop_control:
        loop_var: amq_broker_cluster_node_item
        label: "{{ amq_broker_cluster_node_item.name }}"

    - name: Configure static connectors
      xml:
        path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: >-
          /conf:configuration/core:core/core:connectors/core:connector[@name='{{
          item.name }}']
        value: "{{ amq_broker_cluster_node_item.value | string }}"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: yes
        backup: yes
      when: >-
        not amq_broker_cluster_discovery
        and not amq_broker_cluster_node_item.value is search(ansible_host)
      loop: "{{ amq_broker_cluster_nodes }}"
      loop_control:
        loop_var: amq_broker_cluster_node_item
        label: "{{ amq_broker_cluster_node_item.name }}"

    - name: Remove all static cluster reference connectors
      xml:
        path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: >-
          {{ "/conf:configuration/core:core/core:cluster-connections/"
          + "core:cluster-connection/core:static-connectors" }}
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: yes
        backup: yes
      when: not amq_broker_cluster_discovery

    - name: Add static cluster reference connector
      xml:
        path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: >-
          {{ "/conf:configuration/core:core/core:cluster-connections/"
          + "core:cluster-connection" }}
        add_children:
          - static-connectors:
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: yes
        backup: yes
      when: not amq_broker_cluster_discovery

    - name: Configure static cluster reference connectors
      xml:
        path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: >-
          {{ "/conf:configuration/core:core/core:cluster-connections/"
          + "core:cluster-connection/core:static-connectors" }}
        add_children:
          - connector-ref: "{{ amq_broker_cluster_node_item.name | string }}"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: yes
        backup: yes
      when: >-
        not amq_broker_cluster_discovery
        and not amq_broker_cluster_node_item.value is search(ansible_host)
      loop: "{{ amq_broker_cluster_nodes }}"
      loop_control:
        loop_var: amq_broker_cluster_node_item
        label: "{{ amq_broker_cluster_node_item.name }}"

    - name: Remove cluster connection discovery group reference
      xml:
        path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: >-
          {{ '/conf:configuration/core:core/core:cluster-connections/'
          + 'core:cluster-connection/core:discovery-group-ref' }}
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: yes
      when: not amq_broker_cluster_discovery

    - name: Remove broadcast groups
      xml:
        path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: /conf:configuration/core:core/core:broadcast-groups
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: yes
      when: not amq_broker_cluster_discovery

    - name: Remove discovery groups
      xml:
        path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
        xpath: /conf:configuration/core:core/core:discovery-groups
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: yes
      when: not amq_broker_cluster_discovery
  when: amq_broker_cluster
  tags:
    - role::amq::configure
    - role::amq::configure::clustering
