---
# Configure clustering tasks

- name: Configure static cluster connectors
  when: >-
    amq_broker_cluster | bool
    and not amq_broker_cluster_discovery | bool
  vars:
    etc_broker_path: >-
      {{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker.xml
    etc_broker_connectors_path: >-
      {{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/broker_connectors.xml
    backup: yes
    expected_connectors: >-
      {{ amq_broker_cluster_nodes
      | json_query('[].{name: name, value: value} | sort_by(@, &name)')
      | list }}

  tags:
    - role::amq::configure
    - role::amq::configure::clustering
  block:

    - name: Set cluster-connections
      xml:
        path: "{{ etc_broker_path }}"
        xpath: /conf:configuration/core:core/core:cluster-connections
        set_children: "{{ lookup('template', 'broker_cluster_connections.xml.j2') }}"
        input_type: xml
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: yes
        backup: "{{ backup }}"

    - name: Remove connectors node
      xml:
        path: "{{ etc_broker_path }}"
        xpath: /conf:configuration/core:core/core:connectors
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core

    - name: Template broker_connectors.xml
      template:
        src: broker_connectors.xml.j2
        dest: "{{ etc_broker_connectors_path }}"

    # TODO: Narrow to this include .../xi:include/@href=...broker_connectors.xml
    - name: Count includes
      xml:
        path: "{{ etc_broker_path }}"
        xpath: >-
          /conf:configuration/core:core/xi:include
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
          xi: "http://www.w3.org/2001/XInclude"
        count: yes
      register: broker_connectors_include_count_result

    - name: Add include
      when: broker_connectors_include_count_result.count == 0
      xml:
        path: "{{ etc_broker_path }}"
        xpath: /conf:configuration/core:core/xi:include
        attribute: href
        value: "{{ etc_broker_connectors_path }}"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
          xi: "http://www.w3.org/2001/XInclude"
        pretty_print: yes

    - name: Remove cluster connection discovery group reference
      xml:
        path: "{{ etc_broker_path }}"
        xpath: >-
          {{ "/conf:configuration/core:core/core:cluster-connections/"
          + "core:cluster-connection/core:discovery-group-ref" }}
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: "{{ backup }}"

    - name: Remove broadcast groups
      xml:
        path: "{{ etc_broker_path }}"
        xpath: /conf:configuration/core:core/core:broadcast-groups
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: "{{ backup }}"

    - name: Remove discovery groups
      xml:
        path: "{{ etc_broker_path }}"
        xpath: /conf:configuration/core:core/core:discovery-groups
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        backup: "{{ backup }}"
