---
# Configure jgroups tasks

- name: Configure jgroups file ping
  when: amq_broker_shared_store | bool and amq_jgroups_enabled | bool
  ansible.builtin.template:
    src: jgroups_file_ping.xml.j2
    dest: >-
      {{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/jgroups-file-ping.xml
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    mode: 0640
    backup: yes
  tags:
    - role::amq::configure
    - role::amq::configure::jgroups
