---
# Configure jolokia tasks

- name: Setup jolokia access IP
  vars:
    allowed_origin_value: "*://{{ amq_jolokia_allow_origin }}*"
    xpath_value: '/restrict/cors[allow-origin="{{ allowed_origin_value }}"]'
  block:
    - name: Check jolokia access - IP
      xml:
        path: >-
          {{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/jolokia-access.xml
        xpath: "{{ xpath_value }}"
        count: yes
      register: amq_allow_origin_result

    - name: Configure jolokia access - IP
      when: amq_allow_origin_result.count == 0
      xml:
        path: >-
          {{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/jolokia-access.xml
        xpath: "/restrict/cors/strict-checking"
        insertbefore: yes
        add_children:
          - "allow-origin": "{{ allowed_origin_value }}"
        pretty_print: yes
        backup: yes
  tags:
    - role::amq::configure
    - role::amq::configure::jolokia

- name: Setup jolokia access FQDN
  vars:
    allowed_origin_value: "*://{{ amq_broker_fqdn }}*"
    xpath_value: '/restrict/cors[allow-origin="{{ allowed_origin_value }}"]'
  block:
    - name: Check jolokia access - FQDN
      xml:
        path: >-
          {{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/jolokia-access.xml
        xpath: "{{ xpath_value }}"
        count: yes
      register: amq_allow_origin_result

    - name: Configure jolokia access - FQDN
      when: amq_allow_origin_result.count == 0
      xml:
        path: >-
          {{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/jolokia-access.xml
        xpath: "/restrict/cors/strict-checking"
        insertbefore: yes
        add_children:
          - "allow-origin": "{{ allowed_origin_value }}"
        pretty_print: yes
        backup: yes
  tags:
    - role::amq::configure
    - role::amq::configure::jolokia
