---
# Configure login tasks

- name: Configure login
  ansible.builtin.template:
    src: login.config.j2
    dest: "{{ amq_brokers_dir }}/{{ amq_broker_name }}/etc/login.config"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    mode: 0600
    backup: yes
  tags:
    - role::amq::configure
    - role::amq::configure::login
